export const PLAIN_MESSAGE_MODAL = "PLAIN_MESSAGE_MODAL";

export const GROUPS_MODAL = "GROUPS_MODAL";

export const PROPOSALS_MODAL = "PROPOSALS_MODAL";

export const CONTRACTS_MODAL = "CONTRACTS_MODAL";
